version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://user:password@db:3306/courseInfo"
    volumes:
      - paper_files:/app/paperFiles
      - backup_files:/app/backupFiles  # New volume for backup files
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "courseInfo"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
volumes:
  paper_files:
  backup_files:  # Define the new volume for backup files
